# REFERENCES 
# Github Repository - https://github.com/open-webui/open-webui
# Official Documentation - https://docs.openwebui.com/

services:

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - WEBUI_AUTH=True
      - WEBUI_NAME=MyCompany
      - ENABLE_SIGNUP=True
      - ENABLE_LOGIN_FORM=True
      - DEFAULT_USER_ROLE=pending
      - ENABLE_OLLAMA_API=False
      - ENABLE_OPENAI_API=True
      - OPENAI_API_BASE_URL=
      - OPENAI_API_KEY=
    volumes:
      - ./open-webui:/app/backend/data
    restart: always
