# Official Doc - https://github.com/pgvector/pgvector?tab=readme-ov-file#docker

services:
  
  postgres:
    image: pgvector/pgvector:pg16  # this image installs postgres with pgvector enabled. Change postgres version number is needed
    environment:
      POSTGRES_DB: localdb
      POSTGRES_USER: localuser
      POSTGRES_PASSWORD: localpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      env_file:
        - .env
    depends_on:
      postgres:
        condition: service_healthy  
    ports:
      - "3000:3000"

volumes:
  postgres-data:
