# create secrets using command
# kubectl create secret generic <secret name> --from-literal=key1=value1 --from-literal=key2=value2
# kubectl create secret generic <secret name> --from-file=file1.txt --from-file=file2.txt
# kubectl create secret generic <secret name> --from-file=<foldername>/
# kubectl create secret generic <secret name> --from-env-file=file.txt



# all values are stored in base64 encoded format
# for decoding, use this command - echo -n "value" | base64 --d
apiVersion: v1
data:
  var1: value1
  var2: value2
  var3: value3
kind: Secret
metadata:
  name: my-secret
  namespace: default
type: Opaque



#############

# ITS BETTER TO PASS BASE64 ENCODED VALUES IN YAML FILES, WHILE CREATING SECRETS

apiVersion: v1
data:
  var1: dmFsdWUx  # echo -n "value1" | base64
  var2: dmFsdWUy  # echo -n "value2" | base64
  var3: dmFsdWUz  # echo -n "value3" | base64
kind: Secret
metadata:
  name: my-secret
  namespace: default
type: Opaque