apiVersion: v1
kind: ReplicationController

metadata:
  name: firstreplicationcontroller
  labels:
    pupose: apireplicationcontroller

spec:
  replicas: 5
  selector:
    type: apiapp # rc will maintain pods with this label
  template:
    metadata:
      name: myfirstpod
      labels:
        type: apiapp
    spec:
      containers:
        - name: firstcontainer
          image: coolgourav147/nginx-custom
          env:
            - name: VAR1
              value: var1_value
            - name: VAR2
              value: var2_value
