# NOTE: Container names and ports are not allowed in docker rollout
services:
  nginx-proxy: # proxy is needed, since we can't define ports in docker rollout
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # nginx.conf to be present in same directory as compose file
      - /etc/letsencrypt:/etc/letsencrypt # load ssl certificates into nginx container from host
    restart: always

  backend:
    build:
      context: .
      dockerfile: be.Dockerfile
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"] # ensure that curl is installed in dockerfile, the port is exposed port in dockerfile
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 60s

  frontend:
    build:
      context: .
      dockerfile: fe.Dockerfile
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"] # ensure that curl is installed in dockerfile, the port is exposed port in dockerfile
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s
  
