#!/bin/bash

# Define the path to the file where secrets will be copied
env_file="/home/ubuntu/myapp/myapp.env"

# Clearing the env file to ensure there is no unnecessary variable inside it
> /home/ubuntu/myapp/myapp.env

# Fetch all secrets from GCP secrets manager
# NOTE: The vm should have access to fetch secrets, use service principal
secret_names=$(gcloud secrets list --format="value(name)")

# Loop through each secret name
for secret_name in $secret_names; do
    # Check if secret name starts with 'dev-'
    if [[ $secret_name == dev-* ]]; then
        # Fetch the latest version of the secret
        secret_value=$(gcloud secrets versions access latest --secret="$secret_name")

        # Strip the 'dev-' prefix from the secret name to create the variable name
        var_name=${secret_name#dev-}

        # Check if the variable already exists in the destination file
        if grep -q "^$var_name=" "$env_file"; then
            # Variable exists, replace its value
            sed -i "s#$var_name=.*#$var_name=$secret_value#" "$env_file"
        else
            # Variable doesn't exist, append it to the file
            echo "$var_name=$secret_value" >> "$env_file"
        fi
        # Print the variable name and its updated value
        echo "$var_name=$secret_value"
    fi
done
