# OFFICIAL DOCUMENTATION LINK - https://gotenberg.dev/docs/getting-started/introduction
# Additional configurations - https://gotenberg.dev/docs/configuration

services:
  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"
    environment:
      GOTENBERG_API_BASIC_AUTH_USERNAME: "myuser"
      GOTENBERG_API_BASIC_AUTH_PASSWORD: "myuserpassword"
    command: 
      - "gotenberg"
      - "--api-enable-basic-auth"
      
