# Official github repository - https://github.com/louislam/uptime-kuma

version: '3.8'
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    ports:
      - "8080:3001"
    volumes:
      - "/home/ubuntu/data:/app/data"
    restart: always
