version: '3.8'
services:
  pgadmin:
    image: dpage/pgadmin4 # take latest image from dockehub
    ports:
      - 5050:80  # Map container port 80 to host port 5050
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mycompany.com # this email exists or not doesn't matter
      - PGADMIN_DEFAULT_PASSWORD=pgadminpassword
    user: '$UID:$GID'
    volumes:
      - /home/ubuntu/pgadmin/data:/var/lib/pgadmin
