#Reference:  https://learn.microsoft.com/en-us/azure/azure-functions/functions-how-to-github-actions?tabs=linux%2Cdotnet&pivots=method-template

# Function tier used - Premium Consumption
# This tier is used as the database is in vnet and normal comsumption tier doesnot support vnet integration
# Note: flexible consumption might be a better option in future to save cost but not used right now as it is not a stable product yet.
name: Deploy to Azure Function App

on:
  push:
    branches: [main]

env:
  AZURE_FUNCTIONAPP_NAME: "myfunction" # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "myfunctioncode/" # set this to the path to your function app project, defaults to the repository root
  DOTNET_VERSION: "8.0.x" # set this to the dotnet version to use (e.g. '2.1.x', '3.1.x', '5.0.x')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: "Resolve Project Dependencies Using Dotnet"
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: "${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output"
          publish-profile: ${{ secrets.FUNCTIONAPP_PUBLISH_PROFILE }}
          
