name: PR Notification

on:
  pull_request:
    branches: [ dev, staging, main ]
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch all branches and commits so that it has a base to compare against.

      - name: Setup email recipient
        run: |
          if [ "${{ github.base_ref }}" = "dev" ]; then
            echo "EMAIL_TO=${{ secrets.SMTP_EMAIL_TO_DEV }}" >> $GITHUB_ENV
          elif [ "${{ github.base_ref }}" = "staging" ]; then
            echo "EMAIL_TO=${{ secrets.SMTP_EMAIL_TO_STAGING }}" >> $GITHUB_ENV
          elif [ "${{ github.base_ref }}" = "main" ]; then
            echo "EMAIL_TO=${{ secrets.SMTP_EMAIL_TO_PROD }}" >> $GITHUB_ENV
          fi

      - name: Notify the Team
        uses: hilarion5/send-mail@v1
        with:
          smtp-server: ${{ secrets.SMTP_SERVER }}
          smtp-port: 587
          smtp-secure: false
          from-email: ${{ secrets.SMTP_EMAIL_FROM }}
          to-email: ${{ env.EMAIL_TO }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Pull Request Notification"
          body: |
            This is an email from github actions: ci-cd pipeline.
            Please review and inform the team if you have any questions.
            A Pull Request is created for the branch -- ${{ github.base_ref }}

            PR: ${{ github.base_ref }}  <<<-------  ${{ github.head_ref }} 
            PR Url: ${{ github.event.pull_request.html_url }}
            PR Title - ${{ github.event.pull_request.title }}

            PR Description / Features OR Bug Fixes to be Released
            ${{ github.event.pull_request.body }}
