# REFERENCE: https://learn.microsoft.com/en-us/azure/azure-functions/functions-how-to-github-actions
# NOTE: In modelv2, only 1 function can be deployed in 1 single azure function app

name: Deploy Function
on:
  push:
    branches: [main]

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    env:
      GIT_FunctionApp_Name: "myfunction"
      GIT_FunctionApp_PATH: "PythonFunctions/Model-V2/"
      PYTHON_VERSION: "3.9"
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.GIT_FunctionApp_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd

    - name: 'Deploy Function'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.GIT_FunctionApp_Name }}
        package: ${{ env.GIT_FunctionApp_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true
